name: flac_metadata
description: A cross platform dart package to extract meta data from flac files.
version: 1.0.0
homepage: https://github.com/zengkid/flac_metadata

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  hex: ^0.1.2

dev_dependencies:
  pedantic: ^1.9.0
